### Installing Required Libraries

In [1]:
!pip install nltk
!pip install transformers==4.42.1
!pip install sentencepiece
!pip install spacy
!python -m spacy download en_core_web_sm
!python -m spacy download fr_core_news_sm
!pip install scikit-learn
!pip install torch==2.2.2
!pip install torchtext==0.17.2
!pip install numpy==1.26.0

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 11.4 MB/s eta 0:00:00
  Using cached transformers-4.42.1-py3-none-any.whl.metadata (43 kB)
  Using cached tokenizers-0.19.1-cp312-none-win_amd64.whl.metadata (6.9 kB)
Using cached transformers-4.42.1-py3-none-any.whl (9.3 MB)
Using cached tokenizers-0.19.1-cp312-none-win_amd64.whl (2.2 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.1
    Uninstalling tokenizers-0.22.1:
      Successfully uninstalled tokenizers-0.22.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.0
    Uninstalling transformers-4.57.0:
      Successfully uninstalled transformers-4.57.0
   ---------------------------------------- 0.0/13.9 MB ? eta -:--:--
   ------ --------------------------------- 2.4/13.9 MB 12.2 MB/s eta 0:00:01
   ------------ --------------------------- 4.5/13.9 MB 10.7 MB/s eta 0:00:01
   ------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.14.1 requires numpy<2.3,>=1.23.5, but you have numpy 2.3.3 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.3 which is incompatible.
torchtext 0.17.2 requires torch==2.2.2, but you have torch 2.8.0 which is incompatible.
transformers 4.42.1 requires numpy<2.0,>=1.17, but you have numpy 2.3.3 which is incompatible.


     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     -- ------------------------------------- 0.8/12.8 MB 5.6 MB/s eta 0:00:03
     ---- ----------------------------------- 1.3/12.8 MB 4.2 MB/s eta 0:00:03
     ---- ----------------------------------- 1.6/12.8 MB 3.1 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.8 MB 3.1 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.8 MB 3.1 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.8 MB 3.1 MB/s eta 0:00:04
     ----- ---------------------------------- 1.8/12.8 MB 1.2 MB/s eta 0:00:10
     ----- ---------------------------------- 1.8/12.8 MB 1.2 MB/s eta 0:00:10
     ----- ---------------------------------- 1.8/12.8 MB 1.2 MB/s eta 0:00:10
     ----- ---------------------------------- 1.8/12.8 MB 1.2 MB/s eta 0:00:10
     ------ -------------------------------- 2.1/12.8 MB 857.5 kB/s eta 0:00:13
     ------ -------------------------------- 2.1/12.8 MB 8

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
torchtext 0.17.2 requires torch==2.2.2, but you have torch 2.8.0 which is incompatible.
transformers 4.42.1 requires numpy<2.0,>=1.17, but you have numpy 2.2.6 which is incompatible.


  Using cached torch-2.2.2-cp312-cp312-win_amd64.whl.metadata (26 kB)
Using cached torch-2.2.2-cp312-cp312-win_amd64.whl (198.5 MB)
  Attempting uninstall: torch
    Found existing installation: torch 2.8.0
    Uninstalling torch-2.8.0:
      Successfully uninstalled torch-2.8.0


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.8.0 requires torch==2.8.0, but you have torch 2.2.2 which is incompatible.
torchvision 0.23.0 requires torch==2.8.0, but you have torch 2.2.2 which is incompatible.


  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.0 which is incompatible.
torchvision 0.23.0 requires torch==2.8.0, but you have torch 2.2.2 which is incompatible.


### Importing required libraries

In [40]:
import nltk
nltk.download("punkt")
nltk.download('punkt_tab')
import spacy
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.util import ngrams
from transformers import BertTokenizer
from transformers import XLNetTokenizer

from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from torch.utils.data import Dataset,DataLoader
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
import torch

[nltk_data] Downloading package punkt to C:\Users\Rajveer
[nltk_data]     Gupta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Rajveer
[nltk_data]     Gupta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


### Pytorch  Basic  English Word Tokenizer

In [12]:
input_text=["Hello,I am Rajveer Gupta",
            "Exploring different tokenizers",
           "Learning ML,DL , Gen AI is Wonderful",
           "My Learning in college is going crazy",
           "Extremely Grateful for getting the oppotunity to learn new things",
           "Want to keep exploring new things just like this "]
tokenizer=get_tokenizer("basic_english")
vocab=build_vocab_from_iterator(map(tokenizer,input_text))
def tokens_yield(input_text):
    for sentence in input_text:
        yield tokenizer(sentence)
def print_tokens_and_their_indices(input_text):
    tokens=list(tokens_yield(input_text))
    print("Tokens",tokens)
    print("indices")
    token_indices=[vocab(token) for token in tokens]
    print(token_indices)
print_tokens_and_their_indices(input_text)

Tokens [['hello', ',', 'i', 'am', 'rajveer', 'gupta'], ['exploring', 'different', 'tokenizers'], ['learning', 'ml', ',', 'dl', ',', 'gen', 'ai', 'is', 'wonderful'], ['my', 'learning', 'in', 'college', 'is', 'going', 'crazy'], ['extremely', 'grateful', 'for', 'getting', 'the', 'oppotunity', 'to', 'learn', 'new', 'things'], ['want', 'to', 'keep', 'exploring', 'new', 'things', 'just', 'like', 'this']]
indices
[[20, 0, 21, 8, 30, 19], [1, 11, 33], [3, 27, 0, 12, 0, 15, 7, 2, 35], [28, 3, 22, 9, 2, 17, 10], [13, 18, 14, 16, 31, 29, 6, 25, 4, 5], [34, 6, 24, 1, 4, 5, 23, 26, 32]]


### NLTK Word Tokenizer

In [23]:
input_text=["Hello,I am Rajveer Gupta",
            "Exploring different tokenizers",
           "Learning ML,DL , Gen AI is Wonderful",
           "My Learning in college is going crazy",
           "Extremely Grateful for getting the oppotunity to learn new things",
           "Want to keep exploring new things just like this "]
def tokens_yield(input_text):
    for sentence in input_text:
        yield word_tokenize(sentence)
tokens=tokens_yield(input_text)
for token in tokens:
    print(token)

['Hello', ',', 'I', 'am', 'Rajveer', 'Gupta']
['Exploring', 'different', 'tokenizers']
['Learning', 'ML', ',', 'DL', ',', 'Gen', 'AI', 'is', 'Wonderful']
['My', 'Learning', 'in', 'college', 'is', 'going', 'crazy']
['Extremely', 'Grateful', 'for', 'getting', 'the', 'oppotunity', 'to', 'learn', 'new', 'things']
['Want', 'to', 'keep', 'exploring', 'new', 'things', 'just', 'like', 'this']


### Spacy English Tokenizer Small Model

In [24]:
input_text=["Hello,I am Rajveer Gupta",
            "Exploring different tokenizers",
           "Learning ML,DL , Gen AI is Wonderful",
           "My Learning in college is going crazy",
           "Extremely Grateful for getting the oppotunity to learn new things",
           "Want to keep exploring new things just like this "]
tokenizer=get_tokenizer("spacy",language="en_core_web_sm")
vocab=build_vocab_from_iterator(map(tokenizer,input_text))
def tokens_yield(input_text):
    for sentence in input_text:
        yield tokenizer(sentence)
def print_tokens_and_their_indices(input_text):
    tokens=list(tokens_yield(input_text))
    print("Tokens",tokens)
    print("indices")
    token_indices=[vocab(token) for token in tokens]
    print(token_indices)
print_tokens_and_their_indices(input_text)

Tokens [['Hello', ',', 'I', 'am', 'Rajveer', 'Gupta'], ['Exploring', 'different', 'tokenizers'], ['Learning', 'ML', ',', 'DL', ',', 'Gen', 'AI', 'is', 'Wonderful'], ['My', 'Learning', 'in', 'college', 'is', 'going', 'crazy'], ['Extremely', 'Grateful', 'for', 'getting', 'the', 'oppotunity', 'to', 'learn', 'new', 'things'], ['Want', 'to', 'keep', 'exploring', 'new', 'things', 'just', 'like', 'this']]
indices
[[13, 0, 14, 20, 17, 12], [8, 23, 36], [1, 15, 0, 7, 0, 10, 6, 2, 19], [16, 1, 28, 21, 2, 27, 22], [9, 11, 25, 26, 34, 33, 5, 31, 3, 4], [18, 5, 30, 24, 3, 4, 29, 32, 35]]


# Subword Based Tokenizers

### Bert Tokenizer Working on Word Piece Algorithm 

In [31]:
from transformers import BertTokenizer
from torchtext.vocab import build_vocab_from_iterator

input_text = [
    "Hello, I am Rajveer Gupta",
    "Exploring different tokenizers",
    "Learning ML, DL, Gen AI is Wonderful",
    "My Learning in college is going crazy",
    "Extremely Grateful for getting the opportunity to learn new things",
    "Want to keep exploring new things just like this"
]

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokens_yield(sentences):
    for sentence in sentences:
        yield tokenizer.tokenize(sentence)
vocab = build_vocab_from_iterator(tokens_yield(input_text))
def print_tokens_and_their_indices(input_text):
    tokens=list(tokens_yield(input_text))
    print("Tokens",tokens)
    print("indices")
    token_indices=[vocab(token) for token in tokens]
    print(token_indices)
print_tokens_and_their_indices(input_text)

Tokens [['hello', ',', 'i', 'am', 'raj', '##ve', '##er', 'gupta'], ['exploring', 'different', 'token', '##izer', '##s'], ['learning', 'ml', ',', 'dl', ',', 'gen', 'ai', 'is', 'wonderful'], ['my', 'learning', 'in', 'college', 'is', 'going', 'crazy'], ['extremely', 'grateful', 'for', 'getting', 'the', 'opportunity', 'to', 'learn', 'new', 'things'], ['want', 'to', 'keep', 'exploring', 'new', 'things', 'just', 'like', 'this']]
indices
[[24, 0, 25, 12, 34, 10, 7, 23], [1, 15, 37, 8, 9], [3, 31, 0, 16, 0, 19, 11, 2, 39], [32, 3, 26, 13, 2, 21, 14], [17, 22, 18, 20, 35, 33, 6, 29, 4, 5], [38, 6, 28, 1, 4, 5, 27, 30, 36]]


### Sentence Piece and Unigram Algorithms from XLNet Tokenizers

In [32]:
from transformers import BertTokenizer
from torchtext.vocab import build_vocab_from_iterator

input_text = [
    "Hello, I am Rajveer Gupta",
    "Exploring different tokenizers",
    "Learning ML, DL, Gen AI is Wonderful",
    "My Learning in college is going crazy",
    "Extremely Grateful for getting the opportunity to learn new things",
    "Want to keep exploring new things just like this"
]

tokenizer = XLNetTokenizer.from_pretrained("xlnet-base-cased")

def tokens_yield(sentences):
    for sentence in sentences:
        yield tokenizer.tokenize(sentence)
vocab = build_vocab_from_iterator(tokens_yield(input_text))
def print_tokens_and_their_indices(input_text):
    tokens=list(tokens_yield(input_text))
    print("Tokens",tokens)
    print("indices")
    token_indices=[vocab(token) for token in tokens]
    print(token_indices)
print_tokens_and_their_indices(input_text)

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

Tokens [['▁', 'Hello', ',', '▁I', '▁am', '▁Raj', 've', 'er', '▁Gupta'], ['▁Exp', 'lor', 'ing', '▁different', '▁token', 'izer', 's'], ['▁Learning', '▁', 'ML', ',', '▁', 'DL', ',', '▁Gen', '▁A', 'I', '▁is', '▁', 'Wonderful'], ['▁My', '▁Learning', '▁in', '▁college', '▁is', '▁going', '▁crazy'], ['▁Extreme', 'ly', '▁G', 'rate', 'ful', '▁for', '▁getting', '▁the', '▁opportunity', '▁to', '▁learn', '▁new', '▁things'], ['▁Want', '▁to', '▁keep', '▁exploring', '▁new', '▁things', '▁just', '▁like', '▁this']]
indices
[[0, 8, 1, 27, 31, 29, 20, 12, 26], [22, 16, 14, 34, 47, 15, 19], [2, 0, 10, 1, 0, 7, 1, 25, 21, 9, 3, 0, 11], [28, 2, 39, 32, 3, 38, 33], [23, 17, 24, 18, 13, 36, 37, 45, 44, 6, 42, 4, 5], [30, 6, 41, 35, 4, 5, 40, 43, 46]]


# Working with Data Loaders

In [37]:
input_text = [
    "Hello, I am Rajveer Gupta",
    "Exploring different tokenizers",
    "Learning ML, DL, Gen AI is Wonderful",
    "My Learning in college is going crazy",
    "Extremely Grateful for getting the opportunity to learn new things",
    "Want to keep exploring new things just like this"
]

class CustomDataset(Dataset):
    def __init__(self,sentences):
        self.sentences=sentences
    def __len__(self):
        return len(self.sentences)
    def __getitem__(self,idx):
        return self.sentences[idx]
custom_dataset=CustomDataset(input_text)
dataloader=DataLoader(custom_dataset,batch_size=2,shuffle=True)
for batch in dataloader:
    print(batch)

['Extremely Grateful for getting the opportunity to learn new things', 'Learning ML, DL, Gen AI is Wonderful']
['Want to keep exploring new things just like this', 'My Learning in college is going crazy']
['Hello, I am Rajveer Gupta', 'Exploring different tokenizers']


## Dataloader On Basic English tokenizer of Pytorch

In [41]:
input_text = [
    "Hello, I am Rajveer Gupta",
    "Exploring different tokenizers",
    "Learning ML, DL, Gen AI is Wonderful",
    "My Learning in college is going crazy",
    "Extremely Grateful for getting the opportunity to learn new things",
    "Want to keep exploring new things just like this"
]
# Define a custom data set
class CustomDataset(Dataset):
    def __init__(self, sentences, tokenizer, vocab):
        self.sentences = sentences
        self.tokenizer = tokenizer
        self.vocab = vocab

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        tokens = self.tokenizer(self.sentences[idx])
        # Convert tokens to tensor indices using vocab
        tensor_indices = [self.vocab[token] for token in tokens]
        return torch.tensor(tensor_indices)

# Tokenizer
tokenizer = get_tokenizer("basic_english")

# Build vocabulary
vocab=build_vocab_from_iterator(map(tokenizer,input_text))#both map and yield function are same 
# Create an instance of your custom data set
custom_dataset = CustomDataset(input_text, tokenizer, vocab)

print("Custom Dataset Length:", len(custom_dataset))
print("Sample Items:")
for i in range(6):
    sample_item = custom_dataset[i]
    print(f"Item {i + 1}: {sample_item}")

Custom Dataset Length: 6
Sample Items:
Item 1: tensor([20,  0, 21,  8, 30, 19])
Item 2: tensor([ 1, 11, 33])
Item 3: tensor([ 3, 27,  0, 12,  0, 15,  7,  2, 35])
Item 4: tensor([28,  3, 22,  9,  2, 17, 10])
Item 5: tensor([13, 18, 14, 16, 31, 29,  6, 25,  4,  5])
Item 6: tensor([34,  6, 24,  1,  4,  5, 23, 26, 32])


### Finally Applying DataLoader And Spacy French tokenizer on a French Input Data To Test My Understanding

In [47]:
from torch.nn.utils.rnn import pad_sequence
import torch

def collate_fn(batch):
    # batch is a list of tensors
    return pad_sequence(batch, batch_first=True, padding_value=0)



In [49]:
corpus = [
    "Ceci est une phrase.",
    "C'est un autre exemple de phrase.",
    "Voici une troisième phrase.",
    "Il fait beau aujourd'hui.",
    "J'aime beaucoup la cuisine française.",
    "Quel est ton plat préféré ?",
    "Je t'adore.",
    "Bon appétit !",
    "Je suis en train d'apprendre le français.",
    "Nous devons partir tôt demain matin.",
    "Je suis heureux.",
    "Le film était vraiment captivant !",
    "Je suis là.",
    "Je ne sais pas.",
    "Je suis fatigué après une longue journée de travail.",
    "Est-ce que tu as des projets pour le week-end ?",
    "Je vais chez le médecin cet après-midi.",
    "La musique adoucit les mœurs.",
    "Je dois acheter du pain et du lait.",
    "Il y a beaucoup de monde dans cette ville.",
    "Merci beaucoup !",
    "Au revoir !",
    "Je suis ravi de vous rencontrer enfin !",
    "Les vacances sont toujours trop courtes.",
    "Je suis en retard.",
    "Félicitations pour ton nouveau travail !",
    "Je suis désolé, je ne peux pas venir à la réunion.",
    "À quelle heure est le prochain train ?",
    "Bonjour !",
    "C'est génial !"
]


class CustomDataset1(Dataset):
    def __init__(self,sentences,vocab,tokenizer):
        self.sentences=sentences
        self.vocab=vocab
        self.tokenizer=tokenizer
    def __len__(self):
        return len(self.sentences)
    def __getitem__(self,idx):
        tokens=self.tokenizer(self.sentences[idx])
        token_indices=[self.vocab[token] for token in tokens]
        return torch.tensor(token_indices)
tokenizer=get_tokenizer('spacy',language='fr_core_news_sm')
vocab=build_vocab_from_iterator(map(tokenizer,corpus))
custom_dataset=CustomDataset1(sentences=corpus,vocab=vocab,tokenizer=tokenizer)
dataloader=DataLoader(dataset=custom_dataset,batch_size=4,shuffle=True,collate_fn=collate_fn)
for batch in dataloader:
    print(batch)

tensor([[ 27,   2,   0,   0,   0,   0,   0,   0,   0],
        [  1,  63,  40,  13,  89,  67,  13,  79,   0],
        [ 30,  18,  19,  88,  21,   2,   0,   0,   0],
        [  1,   3,  98,   5, 116,  99,  66,   2,   0]])
tensor([[  1,   3,  70,  46,  10,  81,  78,   5,  21,   0],
        [ 33,  71, 122, 117,  52,   2,   0,   0,   0,   0],
        [ 35,   8,   2,   0,   0,   0,   0,   0,   0,   0],
        [ 12, 119,  39,   8,   5,  84,  59,  54, 115,   0]])
tensor([[  1, 105,  41,   0,   0,   0,   0,   0],
        [ 11,   4,  74,   2,   0,   0,   0,   0],
        [120,  97,  75,   4,   6,  93,  20,   7],
        [ 31,  43,   8,  15,  57,  73,   0,   0]])
tensor([[ 29,  24,  96, 109,  48,  61,  94,  18,   6, 118,  23,  65,   7],
        [  1,   3,  14, 100,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [ 32,  85,  42,  80,  87,   0,   0,   0,   0,   0,   0,   0,   0],
        [ 25, 101,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])
tensor([[  1,   3,  64,  22,  77,  1